version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App_BioStats"
    links:
      - db
    depends_on:
      - db
    ports:
      - "6000:6000"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database_BioStats"
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro